name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from (e.g., 'main' or 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        channelId: live
        projectId: innonative-solutions  # Replace with your Firebase project ID
