name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from (e.g., 'main' or 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: innonative-solutions  # Navigate to the subfolder
      run: npm install

    - name: Build
      working-directory: innonative-solutions  # Navigate to the subfolder
      run: npm run build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools@latest

    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --only hosting --project innonative-solutions
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Pass the token as an environment variable

